kubesphere/community

README.md, cla.md, code-of-conduct.md, contribution/design-proposal-template.md, contribution/design/sig-observability/README.md, developer-guide/development/README.md, sigs.md
the development guide link is incorrect.
=> Fix broken link

STEERING COMMITTEE.md
=> Update STEERING COMMITTEE.md

developer-guide/concepts-and-designs/sig-devops/jenkins-plugin.md
Signed-off-by: runzexia <runzexia@yunify.com>
/cc @shaowenchen @soulseen @zryfish @FeynmanZhou
=> kubesphere jenkins plugin docs

LICENSE, sig-release/README.md, sig-release/releases/release-v200.md, sig-release/releases/release-v201.md, sig-release/releases/release-v202.md, sig-release/releases/release-v210.md, sig-release/releases/release-v211.md
=> solid the info of sig-release

sig-observability/README.md
=> Change sig introduction & add sig members

sig-release/README.md, sig-release/meeting-notes/weekly-status/20200409.md
=> meeting notes 0409

sig-cloud-providers/README.md, sig-cloud-providers/aws/README.md
=> update cloud sig

sig-cloud-providers/aws/roadmap.md, sig-release/meeting-notes/weekly-status/20200416.md
=> weekly status

sig-cloud-providers/OWNERS, sig-storage/OWNERS
Signed-off-by: Xin Wang <wileywang@yunify.com>
=> Add OWNERS in sig cloud providers and sig storage

sig-observability/README.md
=> Add projects to SIG Observability

sig-multitenancy/concepts-and-designs/requestcontext.md, sig-multitenancy/draft/audit-logging.md
Signed-off-by: hongming <talonwan@yunify.com>
@wanjunlei
=> audit log filter design draft

sig-network/concepts-and-designs/kubesphere-network-policy.md
Signed-off-by: Duan Jiong <djduanjiong@gmail.com>
=> add developer doc about kubesphere network policy

sig-edge/README.md
=> Add sig edge

sig-architecture/README.md
=> Add zheng1 to sig architecture

developer-guide/development/how-telepresence-works.md, developer-guide/development/how-to-connect-remote-service.md
=> debug with telepresence

sig-storage/concepts-and-designs/csi-plugin.md
Signed-off-by: Xin Wang <wileywang@yunify.com>
=> Add other storage system

sig-architecture/README.md, sig-edge/README.md
=> adjust sig membership

sig-docs/README.md, sig-docs/localization/how-to-localize-console.md
Signed-off-by: sherlock <sherlockxu@yunify.com>
Add console localization guide
=> Add console localization guide

sig-docs/image-management/image-management.md
Signed-off-by: sherlock <sherlockxu@yunify.com>
add image mg guide
=> add image mg guide

sig-docs/localization/how-to-localize-console.md
Signed-off-by: Sherlock <sherlockxu@yunify.com>
Add desc for console language option
=> Add desc for console language option

sig-network/concepts-and-designs/kubesphere-network-policy.md
Signed-off-by: zackzhangkai <zackzhang@yunify.com>
=> modify sig-network docs

sig-network/concepts-and-designs/kubesphere-network-policy.md
Signed-off-by: Duan Jiong <djduanjiong@gmail.com>
=> update doc about kubesphere network policy

sig-docs/localization/how-to-localize-console.md
Signed-off-by: Sherlock <sherlockxu@yunify.com>
Update loc guide
=> Update loc guide

OWNERS, sig-installation/kubekey/upgrade.md
Signed-off-by: pixiake <guofeng@yunify.com>
=> add kubekey upgrade design

sig-release/releases/release-v300.md
=> add release notes for 3.0.0 (initial version)

sig-docs/installation/community-collaboration-for-v3.0.0.md
=> add community-collaboration-for-v3.0.0.md

sig-docs/installation/community-collaboration-for-v3.0.0.md
=> add huaweicloud to community-collaboration-for-v3.0.0.md

sig-docs/installation/community-collaboration-for-v3.0.0.md
=> assign Azure AKS task

sig-docs/installation/community-collaboration-for-v3.0.0.md
Signed-off-by: Howie66 <haoweili35@gmail.com>
=> add Howie66 as an assignee into this task

sig-docs/installation/community-collaboration-for-v3.0.0.md
/assign @FeynmanZhou   Signed-off-by: lynx <201406007@qq.com>
=> add LiuG-lynx as an assignee into this task

sig-docs/installation/community-collaboration-for-v3.0.0.md
=> get aws eks task

sig-docs/installation/community-collaboration-for-v3.0.0.md
Signed-off-by: Haili Zhang <haili.zhang@outlook.com>
=> docs(installation): add huawei cce and assignee

sig-docs/installation/community-collaboration-for-v3.0.0.md
Signed-off-by: juan-vg <juan@geko.cloud>
=> Digital Ocean reservation by GekoCloud

kubesphere-weekly.md
=> add kubesphere weekly

sig-docs/installation/community-collaboration-for-v3.0.0.md
Signed-off-by: honglei <shenhongleigood@163.com>
=> update pr url for task

sig-docs/installation/community-collaboration-for-v3.0.0.md
=> claim task #4

sig-docs/installation/community-collaboration-for-v3.0.0.md
Claim ks on gke installation guide
=> Claim ks on gke installation guide

sig-docs/installation/community-collaboration-for-v3.0.0.md
Signed-off-by: xuelangos <xuelangos@gmail.com>
=> update installation community-collaboration

sig-docs/installation/community-collaboration-for-v3.0.0.md
=> Update PR link

sig-docs/installation/community-collaboration-for-v3.0.0.md
Signed-off-by: hjwsxl <1453841730@qq.com>
=> adopt the task of KubeSphere on Tencent TKE

sig-docs/installation/community-collaboration-for-v3.0.0.md
Signed-off-by: lynx 201406007@qq.com /assign @FeynmanZhou
=> add LiuG-lynx as an assignee into task 8

sig-release/releases/release-v300.md
=> Adjust metrics server switch desc

sig-docs/installation/community-collaboration-for-v3.0.0.md
Signed-off-by: Juan/Geko <juan@geko.cloud>
=> Digital Ocean reservation by GekoCloud: Set link to PR

sig-virtualization/README.md, sigs.md
=> create sig virtualization

sig-observability/concepts-and-designs/multi-tenant notification.md, sig-observability/concepts-and-designs/notification-manager-v3.1.0.md
Signed-off-by: wanjunlei <wanjunlei@yunify.com>
=> add notification manager design for kubesphere v3.1.0

sig-observability/concepts-and-designs/custom alerting.md
add custom alerting design for kubesphere v3.1.0
/assign @benjaminhuo
=> add custom alerting design for kubesphere v3.1.0

sig-observability/concepts-and-designs/multi-tenant notification.md
Signed-off-by: wanjunlei <wanjunlei@yunify.com>
/assign @benjaminhuo
=> adjust document format

sig-observability/concepts-and-designs/202009_custom-monitoring-enhancement.md
Signed-off-by: huanggze <loganhuang@yunify.com>
=> add custom monitoring enhancement proposal

sig-docs/localization/ZH-CN Localization Task.md
=> Add ZH-CN task list

sig-docs/localization/ZH-CN Localization Task.md
=> claim translation task

sig-docs/localization/ZH-CN Localization Task.md
=> Update task assignment guide name

sig-docs/localization/ZH-CN Localization Task.md
Signed-off-by: jinchen <jinchen_jacean@163.com>
=> Add translator for quickstarts

sig-docs/english-doc-list/KubeSphere 3.0 Documentation List.md
=> Add en doc list

sig-docs/english-doc-list/KubeSphere 3.0 Documentation List (DevOps and Built-in Apps).md
Fix the name based on the comments of https://github.com/kubesphere/community/pull/186.
=> Update doc list name

sig-docs/localization/ZH-CN Localization Task.md
Volunteer to translate the two files.
=> Update ZH-CN Localization Task.md

sig-docs/english-doc-list/KubeSphere 3.0 Documentation List (DevOps and Built-in Apps).md
=> update doc list

sig-docs/localization/ZH-CN Localization Task.md
=> Update ZH-CN task list

sigs-writing-plans.md
=> refine sigs-writing-plans.md

sig-observability/README.md
=> Add sig-observability meeting info

sig-docs/localization/ZH-CN Localization Task.md
Signed-off-by: Haili Zhang <haili.zhang@outlook.com>
=> doc(l10n-task): claim translation owner

sig-docs/localization/ZH-CN Localization Task.md
Signed-off-by: ckyx <tyrone.y093@gmail.com>
=> claim the  tasks

sig-docs/localization/ZH-CN Localization Task.md
Signed-off-by: honglei <shenhongleigood@163.com>
=> get the task

sig-docs/english-doc-list/KubeSphere 3.0 Documentation List (DevOps and Built-in Apps).md
Signed-off-by: Hongliang Wang <hongliangwang@yunify.com>
=> assign apps docs

sig-docs/localization/ZH-CN Localization Task.md
Signed-off-by: Bingo Liao <44894824@qq.com>
=> Claim 'Multi-cluster Management' zh-cn localization

sig-docs/localization/ZH-CN Localization Task.md
add installing-on-linux_index_zh
=> add installing-on-linux_index_zh

sig-devops/README.md
Signed-off-by: harrisonliu5 harrisonliu_5@163.com
=> chore: Update README.md

sig-docs/localization/ZH-CN Localization Task.md
=> Update ZH task list

sig-docs/localization/ZH-CN Localization Task.md
Signed-off-by: honglei <shenhongleigood@163.com>
update PR Link [464](https://github.com/kubesphere/website/pull/464)
=> update PR Link 464

sig-edge/README.md
=> update sig-edge readme

sig-docs/localization/ZH-CN Localization Task.md
update pr link for ZH-CN_Localization_Task.md
Signed-off-by: jinchen <jinchen_jacean@163.com>
=> update pr link for ZH-CN_Localization_Task.md

sig-docs/localization/ZH-CN Localization Task.md
=> get new translate tasks

sig-docs/localization/ZH-CN Localization Task.md
add all-in-one on linux zh docs
=> add all-in-one on linux zh docs

sig-network/concepts-and-designs/ippool.md
Signed-off-by: Duan Jiong <djduanjiong@gmail.com>
=> add doc about ippool

sig-virtualization/README.md
Signed-off-by: Jeff <jeffzhang@yunify.com>
=> update sig virtualization README

sig-observability/concepts-and-designs/multi-tenant notification.md
Signed-off-by: wanjunlei <wanjunlei@yunify.com>
=> update proposal and change the api group

sig-docs/localization/ZH-CN Localization Task.md
=> Signed-off-by: willzhang willzhmic@outlook.com

sig-docs/localization/ZH-CN Localization Task.md
Signed-off-by: willzhang <524869004@qq.com>
=> translate k8s

sig-docs/localization/ZH-CN Localization Task.md
Signed-off-by: zhangwei <pknfe@outlook.com>
+ Upgrade with KubeKey
+ Upgrade with ks-installer
=> get translator task

sig-edge/README.md, sig-observability/README.md
=> Add meeting calendar for observability and edge

sig-docs/localization/ZH-CN Localization Task.md
=> Update ZH-CN guide list

sig-docs/localization/ZH-CN Localization Task.md
=> Add PR link

sig-docs/localization/ZH-CN Localization Task.md
=> Get more task about DevOps and add some PR links.

sig-docs/localization/ZH-CN Localization Task.md
Signed-off-by: willzhang <willzhmic@outlook.com>
=> translate linux overview

sig-docs/localization/ZH-CN Localization Task.md
=> Add a PR link

sig-docs/localization/ZH-CN Localization Task.md
=> Add task translate article in 'DevOps User Guide'

sig-docs/localization/ZH-CN Localization Task.md
=> Add PR links

sig-docs/localization/ZH-CN Localization Task.md
Signed-off-by: Felixnoo <felixliu@yunify.com>
=> task claim on Index Page under App Store-Felixnoo

sig-docs/localization/ZH-CN Localization Task.md
=> Update zhcn list

sig-docs/localization/ZH-CN Localization Task.md
Signed-off-by: Felixnoo <felixliu@yunify.com>
Task claim on Workspace Overview.
=> task-claim-Felixnoo

sig-docs/localization/ZH-CN Localization Task.md
=> Add some articles！

sig-storage/OWNERS, sig-storage/README.md, sig-virtualization/README.md, sigs.md
Signed-off-by: Ray Zhou <ray@yunify.com>
=> Update sig info

sig-docs/localization/ZH-CN Localization Task.md
=> Add PR links.

sig-docs/localization/ZH-CN Localization Task.md
Signed-off-by: Felixnoo <felixliu@yunify.com>
=> task claim

sig-docs/localization/ZH-CN Localization Task.md
=> Add PR link.

sig-docs/localization/ZH-CN Localization Task.md
=> Get some tasks.

sig-docs/localization/ZH-CN Localization Task.md
=> Add PR links! 

developer-guide/development/development-workflow.md
Signed-off-by: daniel-hutao <farmer.hutao@outlook.com>
=> Modify the code format: adjust the symbol at the beginning of the line

sig-advocacy-and-outreach/OWNERS, sig-advocacy-and-outreach/README.md, sig-advocacy-and-outreach/gsoc/README.md
close #291
Hi, @shenhonglei @webup @faweizhao26 @FeynmanZhou @shaowenchen, so glad to work with all of you guys. I'm not sure if I write your names correctly. Please leave your comments if it's not your preferred one.
I'd like to vote @FeynmanZhou as the leader of this SIG. Hopefully, it does not bother you.
* Promote the message of SIG founded
* Call for the first meeting after the Spring festival
=> Add SIG Advocacy and Outreach with the permit of TOC

sig-advocacy-and-outreach/gsoc/README.md, sig-advocacy-and-outreach/gsoc/customize-receiving-users-via-webhook.md, sig-advocacy-and-outreach/gsoc/exposure-of-loadBalancer-service-using-iptables-nat-rules.md, sig-advocacy-and-outreach/gsoc/kubeSphere-jenkins-client-refactor.md, sig-advocacy-and-outreach/gsoc/kubeSphere-tekton-integration.md
Currently, we have three project proposals. Please help to review these ideas
@benjaminhuo @wanjunlei @shaowenchen @FeynmanZhou 
@kubesphere/sig-advocacy-and-outreach
=> Submit project proposals list for GSoC 2021

sig-advocacy-and-outreach/gsoc/kubeSphere-jenkins-client-refactor.md, sig-advocacy-and-outreach/gsoc/kubeSphere-tekton-integration.md
Signed-off-by: Felixnoo <felixliu@yunify.com>
=> Jenkins Client Refactor & Tekton Integration refined.

sig-advocacy-and-outreach/README.md
/cc @kubesphere/sig-advocacy-and-outreach
=> Add a link in the sig advocacy to gsoc

sig-docs/localization/how-to-localize-console.md, sig-docs/localization/kubesphere-console-UI-text-style-guide.md
=> add console UI text style guide

sig-advocacy-and-outreach/README.md, sig-installation/README.md, sig-observability/README.md
Signed-off-by: daniel-hutao <farmer.hutao@outlook.com>
=> Add member: daniel-hutao

sig-installation/README.md
Signed-off-by: light4 lightning1141@gmail.com
fix KubeKey link
=> Fix the broken link of kubekey

sig-advocacy-and-outreach/README.md, sig-advocacy-and-outreach/gsoc/README.md, sig-advocacy-and-outreach/summer-ospp/OWNERS, sig-advocacy-and-outreach/summer-ospp/README.md
/cc @kubesphere/sig-advocacy-and-outreach
=> Add more details of sig advocacy and outreach

sig-advocacy-and-outreach/summer-ospp/kubeSphere-tekton-integration.md, sig-advocacy-and-outreach/summer-ospp/kubeSphere-tekton-integration_zh-CN.md
Signed-off-by: shaowenchen <mail@chenshaowen.com>
/assign @kubesphere/sig-devops
=> improvement: tekton summer ospp

sig-advocacy-and-outreach/summer-ospp/README.md, sig-advocacy-and-outreach/summer-ospp/README_zh-CN.md, sig-advocacy-and-outreach/summer-ospp/TODO-LIST.md, sig-advocacy-and-outreach/summer-ospp/customize-notification-receivers-using-a-webhook.md, sig-advocacy-and-outreach/summer-ospp/customize-notification-receivers-using-a-webhook_zh-CN.md, sig-advocacy-and-outreach/summer-ospp/support-send-notifications-to-pushover_zh-CN.md
Signed-off-by: honglei <hongleishen@hotmail.com>
=> update summer 2021's proposals

sig-advocacy-and-outreach/summer-ospp/README.md, sig-advocacy-and-outreach/summer-ospp/README_zh-CN.md, sig-advocacy-and-outreach/summer-ospp/kubesphere-gatekeeper-integration.md, sig-advocacy-and-outreach/summer-ospp/kubesphere-gatekeeper-integration_zh-CN.md
Signed-off-by: hongming <talonwan@yunify.com>
=> Add gatekeeper inegration project proposal

sig-advocacy-and-outreach/summer-ospp/KubeSphere-SAML-integrations.md, sig-advocacy-and-outreach/summer-ospp/KubeSphere-SAML-integrations_zh-CN.md, sig-advocacy-and-outreach/summer-ospp/README.md, sig-advocacy-and-outreach/summer-ospp/README_zh-CN.md
Signed-off-by: Roland.Ma <rolandma@yunify.com>
/cc @FeynmanZhou  @shenhonglei
=> Add SAML authentication  inegration proposal

sig-devops/OWNERS, sig-devops/README.md
Signed-off-by: johnniang <johnniang@fastmail.com>
=> Add JohnNiang into devops approver and reviewer list

developer-guide/development/README.md, developer-guide/development/cherry-picks.md
Signed-off-by: hongming <talonwan@yunify.com>
=> Add cherry pick guide

sig-serverless/OWNERS, sig-serverless/README.md
=> Add docs for sig-serverless

sig-devops/README.md
hi @zryfish and @shaowenchen, thanks for all you guys did a lot of contributions for the DevOps SIG.
Consider we didn't see you in the SIG meeting or other community activities in the DevOps area. I'm not sure if you are still interested in this area. I am going to move you to the alumni list if you prefer to pay attention to other areas.
The community is always looking forward to seeing you again.
/cc @kubesphere/sig-devops
=> Update the member list of SIG DevOps

sig-observability/README.md
Signed-off-by: Benjamin Huo <benjamin@kubesphere.io>
=> Adjust meeting info

sig-architecture/OWNERS, sig-architecture/README.md
Signed-off-by: Ray Zhou <ray@yunify.com>
=> Update member list for arch sig

sig-microservice/concepts-and-designs/KubeSphere-gateway-operator-design.md
Signed-off-by: Roland.Ma <rolandma@kubesphere.io>
=> Add KubeSphere Gateway Operator design doc

sig-advocacy-and-outreach/ospp-2022/README.md, sig-advocacy-and-outreach/ospp-2022/README_zh-CN.md
Signed-off-by: faweizhao26 <faweizhao@kubesphere.io>
=> add ospp 2022

sig-advocacy-and-outreach/ospp-2022/openfunction-dapr-elastic-app-runtime.md
Signed-off-by: wanjunlei <wanjunlei@kubesphere.io>
=> Openfunction dapr elastic app runtime for ospp 2022

sig-advocacy-and-outreach/ospp-2022/kubeeye-console2.0.md
Add KubeEye Console2.0 project proposal for ospp2022
=> Add KubeEye Console2.0 project proposal for ospp2022

sig-advocacy-and-outreach/ospp-2022/README_zh-CN.md, sig-advocacy-and-outreach/ospp-2022/kubesphere-sharing-secret-plugin_zh-CN.md
Add KubeSphere sharing secret plugin project proposal to OSPP 2022.
=> Add kubesphere sharing secret plugin project proposal

sig-advocacy-and-outreach/ospp-2022/README_zh-CN.md, sig-advocacy-and-outreach/ospp-2022/kubekey-phase-run_zh-CN.md
Add "kubekey phase run" proposal to OSPP 2022.
=> add kubekey phase run

sig-devops/README.md
I made this decision due to not having enough time to maintain this SIG as a leader.
=> Make Rick as a regular member of the DevOps SIG

sig-advocacy-and-outreach/ospp-2023/openfunction-function-trigger.md
add ospp-2023 proposal: OpenFunction function trigger
=> add ospp-2023 proposal: OpenFunction function trigger

sig-advocacy-and-outreach/ospp-2023/kubesphere-s2i-upgrade-with-buildpacks_zh-CN.md
add: kubesphere-s2i upgrade topic
=> kubesphere-s2i upgrade with buildpacks

ksap-ambassador-program/OWNERS, ksap-ambassador-program/README.md
Ambassadorship Program repo base added.
@calvinyv 
@faweizhao26
=> Ambassadorship Program

ksap-ambassadorship-program/README.md, ksap-ambassadorship-program/ambassador-contents/README.md, ksap-ambassadorship-program/ambassadors/README.md, ksap-ambassadorship-program/certificates/README.md, ksap-ambassadorship-program/meetings/README.md, ksap-ambassadorship-program/workgroups/README.md
Added more information about the program. Added folders for activities after the program.
=> update Readme.md and folders

ksap-ambassadorship-program/ambassador-contents/events/graphic-design/README.md, ksap-ambassadorship-program/ambassador-contents/events/presentation/README.md
Event folders have been added for ambassadors to use in their events.
=> added events folder
